# Files to exclude from build
exclude: ['readme.md']

# Website name
name: Example

# Website slogan
slogan: This is my site. It's awesome.

# Header menu 
header-navigation:
- text: Home
  url: /index.html
- text: Page 1
  url: /page1.html
- text: Page 2
  url: /page2.html
- text: Page 3
  url: /page3.html

# Default meta description and keywords
description: Meta description goes here (will be used globally, override it per page)
keywords: Meta keywords goes here (will be used globally, override it per page)
