# Files to exclude from build
exclude: ['readme.md']

# Website name
name: '#Euromaidan'

# Website slogan
slogan: Live Videos

# Header menu 
#header-navigation:
#- text: Videos
#  url: /index.html
#- text: Ukraine
#  url: /page1.html
#- text: World
#  url: /page2.html

# Default meta description and keywords
description: Live videos from Kyiv in one page. 
keywords: euromaidan, live videos

og_title: '#Euromaidan'
og_description: 'Live videos from Kyiv in one page.'
og_image: 'assets/img/maidan.jpg'