# Files to exclude from build
exclude: ['readme.md']

# Website name
name: '#Euromaidan'

# Website slogan
slogan: Live Videos

# Header menu 
#header-navigation:
#- text: Videos
#  url: /index.html
#- text: Ukraine
#  url: /page1.html
#- text: World
#  url: /page2.html

# Default meta description and keywords
description: 
keywords: 
