# Files to exclude from build
exclude: ['readme.md']

# Website name
name: '#Euromaidan'

# Website slogan
slogan: Live

# Default meta description and keywords
description: Live videos from Kyiv in one page. Please consider going to the center of the city to support others. 
keywords: euromaidan, live videos, kyiv, kiev, ukraine, видео, майдан

og_title: '#Euromaidan'
og_description: 'Live videos from Kyiv in one page.'
og_image: 'http://maidan.alexisyes.com/assets/img/maidan.jpg'

# Header menu 
header-navigation:
- text: Videos
  url: /index.html
- text: Lulz
  url: /lulz.html
- text: Instagram
  url: /instagram.html
- text: Twitter
  url: /twitter.html