<footer>
  <hr/ >
  <div class="row">
    <div class="col-lg-3">
      <address>
        <strong>Twitter, Inc.</strong><br>
        795 Folsom Ave, Suite 600<br>
        San Francisco, CA 94107<br>
        <abbr title="Phone">P:</abbr> (123) 456-7890
      </address>
    </div>
    <div class="col-lg-3">
      <ul class="nav nav-pills nav-stacked">
        <li><a>Item 1</a></li>
        <li><a>Item 2</a></li>
        <li><a>Item 3</a></li>
      </ul>
    </div>
    <div class="col-lg-3">
      <button type="button" class="btn btn-default">Default</button>
    </div>
    <div class="col-lg-3">
      <button type="button" class="btn btn-danger">Danger</button>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <hr />
      <p class="text-center">&copy; Copyright no one at all. Go to town.</p>
    </div>
  </div>
</footer>